[project]
name = "demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flax>=0.10.1",
    "jax[cuda12]>=0.4.35",
    "magic-wormhole>=0.17.0",
    "numpy>=2.1.3",
    "orbax>=0.1.9",
]
